spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  servlet:
    multipart:
      max-file-size: 50MB
